nohup ./run_scripts/treat/run_desktop_P04.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P04.log &
nohup ./run_scripts/treat/run_desktop_P06.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P06.log &
nohup ./run_scripts/treat/run_desktop_P08.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P08.log &
nohup ./run_scripts/treat/run_desktop_P10.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P10.log &
nohup ./run_scripts/treat/run_desktop_P11.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P11.log &
nohup ./run_scripts/treat/run_desktop_P13.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P13.log &
nohup ./run_scripts/treat/run_desktop_P16.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P16.log &
nohup ./run_scripts/treat/run_desktop_P17.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P17.log &
nohup ./run_scripts/treat/run_desktop_P19.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P19.log &
nohup ./run_scripts/treat/run_desktop_P20.sh > /mnt/c/Users/jz964/Documents/1_data_assimilation_spruce/TECO-SPRUCE_v3_1/outputs/outlogs/out_P20.log &