nohup ./run_scripts/acc_mac/run_desktop_P04.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P04.log &
nohup ./run_scripts/acc_mac/run_desktop_P06.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P06.log &
nohup ./run_scripts/acc_mac/run_desktop_P08.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P08.log &
nohup ./run_scripts/acc_mac/run_desktop_P10.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P10.log &
nohup ./run_scripts/acc_mac/run_desktop_P11.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P11.log &
nohup ./run_scripts/acc_mac/run_desktop_P13.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P13.log &
nohup ./run_scripts/acc_mac/run_desktop_P16.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P16.log &
nohup ./run_scripts/acc_mac/run_desktop_P17.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P17.log &
nohup ./run_scripts/acc_mac/run_desktop_P19.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P19.log &
nohup ./run_scripts/acc_mac/run_desktop_P20.sh > /Users/jianzhou/Documents/1_MyWorks/1_SPRUCE_cases/1_SPRUCE_DA/1_code_DA/TECO-SPRUCE_v3_1/outputs/outlogs/out_P20.log &